[[build]
  publish = "dist"        # Correct publish directory for Vite output
  command = "npm run build"   # Correct build command

[[headers]]
  for = "/"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"


[[plugins]]
  package = "@netlify/plugin-vite" 